services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=subtracker'
      - 'POSTGRES_PASSWORD=subtracker'
      - 'POSTGRES_USER=subtracker'
    ports:
      - '5432'
